TOP_DIR=..
LXC_ROOT=/tmp/lxc-node

DEMO_ID=7

LXC_NODES=6

PLATFORMS=platform.xml

# platforms to generate automatically from template
GENERATED_PLATFORMS=             

GENERATED_EVENTDAEMONS=         

GENERATED_GPSDLOCATIONAGENTS= 

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=          \
 routing1.conf                   \
 routing2.conf                   \
 routing3.conf                   \
 routing4.conf                   \
 routing5.conf                   \
 routing6.conf                   \
 routing7.conf                   \
 routing8.conf                                   

GENERATED_EXTRA=                 \
 eelgenerator.xml

include ../rules.mk
