TOP_DIR=..
LXC_ROOT=/tmp/lxc-node

DEMO_ID=6

LXC_NODES=4

NEM_XML=csmacdnem.xml

PLATFORMS=platform.xml

# platforms to generate automatically from template
GENERATED_PLATFORMS=            

GENERATED_EVENTDAEMONS=          

GENERATED_GPSDLOCATIONAGENTS=    

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=          \
 routing1.conf                   \
 routing2.conf                   \
 routing3.conf                   \
 routing4.conf                  


include ../rules.mk
